- name: Shutdown system
  community.general.shutdown:
    delay: '{{ shutdown_delay | default(0) }}'
  tags: 
    - shutdown
  when: shutdown is defined and (shutdown | bool)
  
- name: Reboot system
  reboot:
    pre_reboot_delay: '{{ reboot_delay | default(0) }}'
    post_reboot_delay: 60
  tags:
    - reboot
  when: reboot is defined and (reboot | bool)
