- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade apt packages
  apt:
    upgrade: safe

- name: Install git, tmux, vim, zsh
  apt:
    name: 
      - git
      - tmux 
      - vim
      - zsh
    state: present

- name: Set .tmux.conf
  copy:
    src: files/tmux.conf
    dest: '/home/{{ ansible_ssh_user }}/.tmux.conf'
    owner: '{{ ansible_ssh_user }}'
    group: pi
    mode: u=rw,g=r,o=r

- name: Change shell in /etc/passwd to use /usr/bin/zsh
  replace:
    path: /etc/passwd 
    regexp: (?<=pi:)\/(.)+\/bash$
    replace: /usr/bin/zsh

- name: Download ZSH install script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ ansible_ssh_user }}/zsh-install.sh
    mode: u=rwx,g=rx,o=rx

- name: Check if oh-my-zsh is already installed
  stat:
    path: /home/{{ ansible_ssh_user }}/.oh-my-zsh
  become: yes
  become_user: root
  register: zsh_check

- name: Run the ZSH install script if oh-my-zsh is not already installed
  command:
    cmd: /home/{{ ansible_ssh_user }}/zsh-install.sh --unattended
  when: not zsh_check.stat.exists

- name: Copy preferred .zshrc config
  copy:
    src: files/zshrc
    dest: /home/{{ ansible_ssh_user }}/.zshrc
  

- name: Copy local vimrc file
  copy:
    src: files/vimrc
    dest: /home/{{ ansible_ssh_user }}/.vimrc